server:
  port: 8083
  
spring:
  application:
    name: API-GATEWAY
    
    
  cloud:
    gateway:
      routes:
        - id: CUSTOMER-SERVICE
          uri:
            lb://CUSTOMER-SERVICE
          predicates:
          - Path=/customers/**
                 
        - id: ITEM-SERVICE
          uri:
            lb://ITEM-SERVICE
          predicates:
          - Path=/items/**
          
        - id: ITEM-SERVICE
          uri:
            lb://ITEM-SERVICE
          predicates:
          - Path=/loadbalance/status/check
             
        - id: SALES-ORDER-SERVICE
          uri:
            lb://SALES-ORDER-SERVICE
          predicates:
          - Path=/orders/**
          
      
          
          
          
        